service:
  name: 'fdht:sync'
  connection: 'RESTHashtableConn'
fdht: 
  manager:
    ip: "127.0.0.1"
    port: 3000
  sync:
    ip: "0.0.0.0"
    port: 3001
udht:
  manager:
    ip: "127.0.0.1"
    port: 3002
  sync:
    ip: "0.0.0.0"
    port: 3003
