LOG_NAME = "server.log"
CONFIG_FILE = "./config.yaml"
ENCODING="utf-8"
SOCKET_CONNECTION_LIMIT=10
THREAD_POOL_LIMIT = 10

SCHEDULER_TABLE_SYNC_JOB_HOUR_INTERVAL=5
SCHEDULER_PEER_SYNC_JOB_HOUR_INTERVAL=100